export const projects = [
  {
    title: '별나린밤',
    description: "인플루언서, 사업을 준비하는 사람들을 위해 키워드 검색 결과를 제공해주는 웹 사이트",
    image: '/images/star/main.jpg',
    tags: ['React', 'Typescript', 'Jenkins', 'SWR', 'Next.js'],
    source: 'https://github.com/IMHOJEONG/SSAFY_special_project',
    visit: 'https://github.com/IMHOJEONG/SSAFY_special_project',
    id: 0,
  },
  {
    title: 'OGYM',
    description: "코로나 시대에 헬스장에 갈 수 없는 사람들을 위한 트레이너 매칭 프로젝트, ",
    image: '/images/ogym/background.jpg',
    tags: ['React', 'Recoil', 'Typescript', 'Openvidu',
    'Jenkins', 'JWT'],
    source: 'https://github.com/IMHOJEONG/SSAFY_common_project',
    visit: 'https://github.com/IMHOJEONG/SSAFY_common_project',
    id: 1,
  },
  {
    title: 'HappyHouse',
    description: "부동산 관련 정보를 실시간으로 제공해주는 서비스",
      image: '/images/3.jpg',
      tags: ['Vue.js', 'Node.js', 'Vuetify', 'Vuex', 'Selenium', 'mongoDB'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Disconnect Openshift Container Platform (DevSecOps)',
    description: "OCP 버전 4.4, 국방부, 관공서와 같은 보안이 중시되는 곳처럼 외부 인터넷을 사용할 수 없는 경우, Private Cloud 환경을 구성해야 합니다. DevSecOps Pipeline을 구성하였습니다.",
    image: '/images/openshift/cicd_pipeline.jpg',
    tags: ['Jenkins', 'RedHat Openshift', 'Firebase'],
    source: 'https://drive.google.com/file/d/1VRgUDPvkxwnQoplCqSJwzntnv-hQ3RtU/view?usp=sharing',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Pumpitition',
    description: "항상 컴퓨터 앞에 앉아있는 개발자들을 위한 운동 측정 웹 서비스",
    image: '/images/pumpitition/main.jpg',
    tags: ['HTML', 'CSS', 'JAVASCRIPT'],
    source: 'https://drive.google.com/file/d/1tXNxiuyloixwj4w41pjTTVJTqtt4kVZp/view?usp=sharing',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Kakao Enterprise Cloud Resource Console',
    description: "카카오 엔터프라이즈 클라우드 리소스를 관리하기 위한 콘솔 프로젝트",
    image: '/images/kakao_enterprise/kakao_enterprise.jpg',
    tags: ['Jenkins', 'RedHat Openshift', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2019, text: '2019 OpenHack Hackerthon', },
  { year: 2020, text: 'CCCR Hybrid Cloud Education', },
  { year: 2020.11, text: '카카오 엔터프라이즈 클라우드 개발 인턴', },
  { year: 2021, text: 'SSAFY(삼성 SW 교육 아카데미) 수료', },
];